# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Item

# Model Form Field configuration
form: $/icefox/service/models/item/fields.yaml

# Model Class name
modelClass: IceFox\Service\Models\Item

# Default redirect location
defaultRedirect: icefox/service/items

# Create page
create:
    title: icefox.service::lang.controllers.items.create_service
    redirect: icefox/service/items/update/:id
    redirectClose: icefox/service/items

# Update page
update:
    title: icefox.service::lang.controllers.items.edit_service
    redirect: icefox/service/items
    redirectClose: icefox/service/items

# Preview page
preview:
    title: Preview Item
